title: 'Jon Glick'
author:
  name: 'Jon Glick'
  email: jonathanpglick@gmail.com
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
description: 'Developer, developing.'
menu:
social:
  -
    text: Github
    url: 'https://github.com/getgrav/grav'
